dada:
  tuda:
    framework:
      messaging:
        decompose-routing-key: true
        cache:
          in-memory:
            size: 100
        store-only-cancelable: true
        saga:
          ttl: 10m
          enabled: false
      domains:
        queue:
          naming:
            per-service: true