dada:
  tuda:
    framework:
      messaging:
        decomposeRoutingKey: true
        cache:
          inMemory:
            size: 100
        store-only-cancelable: true
        saga:
          ttl: 10m
          enabled: false
      domains:
        queue:
          naming:
            perService: true